### ISSUE TITLE
cannot load such file -- aws-sdk-cloudformation

### ISSUE THREAD

**Issue by Mathdon** [inspec/inspec-aws#108]
### 🎛 Description

When trying to include this resource in my project I get the error>
cannot load such file -- aws-sdk-cloudformation
when running my tests

### 🌍 InSpec and Platform Version

INSPEC version 4.6.9

### 🤔 Replication Case

I followed the Readme:
 inspec init profile my-profile

Added the dependency to the inspec.yml file:
name: my-profile
title: My own AWS profile
version: 0.1.0
inspec_version: '>= 2.2.7'
depends:
   name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
   platform: aws

Run:
inspec vendor my-profile --overwrite

Then run:
inspec exec my-profile -t aws://

Which outputs:
Traceback (most recent call last):
        30: from /usr/local/bin/inspec:155:in `<main>'
        29: from /usr/local/bin/inspec:155:in `load'
        28: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.9/bin/inspec:11:in `<top (required)>'
        27: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/base_cli.rb:31:in `start'
        26: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/cli.rb:297:in `exec'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:121:in `run'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:93:in `load'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:93:in `each'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:99:in `block in load'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `load_libraries'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `each_with_index'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `each'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:248:in `block in load_libraries'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:256:in `load_libraries'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:134:in `load_libraries'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:134:in `each'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:136:in `block in load_libraries'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:149:in `load_library_file'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:160:in `load_with_context'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:160:in `instance_eval'
         6: from libraries/aws_alb.rb:3:in `load_with_context'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:26:in `require'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:26:in `eval'
         3: from libraries/aws_backend.rb:4:in `create'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:13:in `require'
         1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk-cloudformation (LoadError)

**Comment by Mathdon** [comment]
Issue resolved

**Comment by rmoles** [comment]
Hi @Mathdon. Thanks for raising an issue.
I'm glad this has now been resolved. Would it be possible for you to post your solution for anyone else who may have this same issue?

**Comment by Mathdon** [comment]
Hi

Yeah I will do, It was an uninstall re install thing so it must have been a local environment issue.

Cheers

Math

On 8 Jul 2019, at 10:39, Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Mathdon<https://github.com/Mathdon>. Thanks for raising an issue.
I'm glad this has now been resolved. Would it be possible for you to post your solution for anyone else who may have this same issue?
