### ISSUE TITLE
Add test coverage for aws_internet_gateway

### ISSUE THREAD

**Issue by sap-sm** [inspec/inspec-aws#109]
## Detailed Description
Trying to achieve 100% test coverage of my AWS/Terraform deployment.  `aws_internet_gateway` appears to be missing.

## Possible Implementation
```
describe aws_internet_gateway(Name: "internet_gateway_name") do
  it { should exist }
  its('vpc_name'){ should be "name_of_vpc_it_should_belong_to" }
  its('state'){ should eq "attached|detached" }
end
```
I prefer to use name based lookups because I don't know what the actual AWS IDs/ARNs will be until after the infra is deployed.  It would be awesome if we could do name based lookups on all resource types that support names.

**Comment by JQUINONES82** [comment]
I have a specific use case where I would want something like this.  I have some use cases where a VPC is completely private and uses private links or routes back through the DC for security inspection.

Not sure if we could add the above or something like 


describe aws_vpc(vpc_id: 'vpc-123456789') do 
  its('igw') { should be attached|notattached }
  its('natgw') { should be attached|notattched }
end

This would help ensure or prove to auditors that highly secure VPCs are only using private links or routing back through the datacenter for highly secure traffic.
