### ISSUE TITLE
aws_dynamodb_table doesn't let you test more than one global_secondary_indexes

### ISSUE THREAD

**Issue by rgevaert** [inspec/inspec-aws#126]
# Describe the problem

Currently the code only makes it possible to test the first global index.

It would be more convenient to test more than one. As the different indexes can have different settings.

## Possible Solution

Currently I have no idea how this could be retrofitted in the current implementation. Maybe @rmoles has any idea as I see he was involved in https://github.com/inspec/inspec-aws/pull/91

**Comment by r-fennell** [comment]
@rmoles

**Comment by rgevaert** [comment]
For now i created a custom resource that can be called like this.  I added a flag for the index_type.
```
    describe dynamodb_table_index(table_name: 'testtable',
                                  index_type: 'global_secondary',
                                  index_name: 'DailyAverageIndex',
                                  key_schema_attributes: %w[DailyAverage HighWater]) do
      it { should exist }
      its('projection.projection_type') { should eq 'INCLUDE' }
      its('projection.non_key_attributes') { should eq %w[HashKey RangeKey] }
      its('key_schema_count') { should be 2 }
      its('key_schema_DailyAverage') { should cmp 'HASH' }
      its('key_schema_HighWater') { should cmp 'RANGE' }
    end
```

**Comment by omerdemirok** [comment]
@rgevaert, thanks for opening an issue.
If a dynamo DB has  `glabol_secondary_indexes` defined, its properties can be reached by prepending `global_sec_indexes_` in front of the property name as documented [here](https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_dynamodb.md#properties). 

Example for testing `index_name` of the global secondary indexes:
```ruby
describe aws_dynamodb_table(table_name: 'my_table') do
  its('global_sec_indexes_index_name') { should eq 'DailyAverageIndex' }
  its('global_sec_indexes_index_status') { should eq 'ACTIVE' }
end
```
For additional properties, please see [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TableDescription.html#DDB-Type-TableDescription-GlobalSecondaryIndexes).

I hope this resolves the issue.

**Comment by rgevaert** [comment]
Ok thank you!

**Comment by omerdemirok** [comment]
The resource ignores the global secondary indexes if there is more than one.
