### ISSUE TITLE
aws_iam_access_keys - created_days_ago not evaluating correctly

### ISSUE THREAD

**Issue by robh-wirehive** [inspec/inspec-aws#135]
I have created this control block for an IAM Access Keys, which can dynamically scale the number of usernames to an account. This is working well, but for some reason i cannot seem to get a correct evaluation of the 'created_days_ago' property

```
control '90DayAccess-users' do
    impact 0.8
    title 'Users: 90DayAccess'
    desc 'Make sure all users APIKeys have rotated in last 90 days'
    tag 'aws','users','90days'

    # Get hash of entries
    keyEntries=aws_iam_access_keys.entries

    #Filter on username only
    keyUsername = (keyEntries.map{|keys| keys["username"]})

    # Loop on each username (Dynamic sized)
    for username in keyUsername

        describe aws_iam_access_keys.where(username: username) do
            its('created_days_ago') { should be <= [90] }  
        end
    end
end
```

![bug-report](https://user-images.githubusercontent.com/55236372/65880531-d7ad6300-e389-11e9-8530-951bf42b9a1c.PNG)

The screenshot shows that all tests fail, but i would expect the first to report success, as 0 is less than 90 days. i have tried a number of different >, >=, < tests, but all are giving incorrect results

**Comment by robh-wirehive** [comment]
I have found a work around to use the singular aws_iam_access_key describe block on conjunction with the plural

```
control 'APIRotation-users' do
    impact 0.8
    title 'Users: API Rotation'
    desc 'Make sure all users APIKeys have rotated in last X days'
    tag 'aws','users','rotation', 'iam'

    expiryDays=90

    # Get hash of entries
    keyEntries=aws_iam_access_keys.entries

    #Filter on username only
    keyUsername = (keyEntries.map{|keys| keys["username"]})

    # Loop on each username (Dynamic sized)
    for username in keyUsername

        describe aws_iam_access_key(username: username) do
            it { should be_active }
            its('create_date') { should be > Time.now - expiryDays * 86400 }
        end

        describe aws_iam_access_keys.where(username: username) do
            its('ever_used') { should eq [true] }
        end
    end
end
```

**Comment by omer-chefio** [comment]
Hi, @robh-wirehive, thanks for opening an issue.

The latter method is the preferred use of plural and singular resources in a combination.
As this is resolved, I'm going to close this issue.
