### ISSUE TITLE
Fix Markdown markup for the aws_security_group resource

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-aws#137]
@multani commented on [Tue Sep 10 2019](https://github.com/inspec/inspec/pull/4462)

## Description
The formatting of the [aws_security_group](https://www.inspec.io/docs/reference/resources/aws_security_group/) resource has several bugs. The "Matchers" section is particularly affected.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

---

@chef-expeditor[bot] commented on [Tue Sep 10 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-529921303)

Hello multani! Thanks for the pull request!

Here is what will happen next:

1. Your PR will be reviewed by the maintainers.
2. Possible Outcomes
  a. If everything looks good, one of them will approve it, and your PR will be merged.
  b. The maintainer may request follow-on work (e.g. code fix, linting, etc). We would encourage you to address this work in 2-3 business days to keep the conversation going and to get your contribution in sooner.
  c. Cases exist where a PR is neither aligned to Chef InSpec's product roadmap, or something the team can own or maintain long-term. In these cases, the maintainer will provide justification and close out the PR.

Thank you for contributing!

---

@codeclimate[bot] commented on [Tue Sep 10 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-529921909)

Code Climate has analyzed commit cee32994 and detected **0 issues** on this pull request.

View more on [Code Climate](https://codeclimate.com/github/inspec/inspec/pull/4462).

---

@multani commented on [Tue Sep 10 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-529932237)

Also, it's not clear whether this documentation should be fix in the https://github.com/inspec/inspec or the https://github.com/inspec/inspec-aws repository?

---

@clintoncwolfe commented on [Tue Sep 10 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-530025110)

It should definitely be submitted to the inspec/inspec-aws repo. Thanks!

---

@multani commented on [Tue Sep 10 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-530124235)

@clintoncwolfe I'd be glad to port the patch to inspec-aws but AFAIK, the current documentation at https://inspec.io still uses the Markdown from inspec/inspec, right?
For example, the content of the same doc in the inspec-aws repository [contains a properties table](https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_security_group.md#properties) which is not in https://www.inspec.io/docs/reference/resources/aws_security_group/

This is a bit confusing, it looks like if I move this patch to inspec-aws, the official documentation will still be partly broken... :/

---

@clintoncwolfe commented on [Wed Sep 11 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-530434998)

So, the way this is *supposed* to work is that the inspec-aws version is the most accurate; when we update the inspec.io website we pull their markdown files and publish them; and we only keep the old aws resource files in core for people who did not update their dependencies in inspec 4.

Issues #4471 and #4470 and your #4463 all indicate that we need to work on the publishing system. All that said, the right place for any info you have is inspec/inspec-aws's markdown files.

---

@kekaichinose commented on [Mon Sep 30 2019](https://github.com/inspec/inspec/pull/4462#issuecomment-536694652)

@multani as we work to address the publishing system issues that @clintoncwolfe mentioned above, are you okay with us moving this issue over to inspec/inspec-aws project to be addressed?

Unless there's any objects, we'll just go ahead and migrate it over there for you.

**Comment by multani** [comment]
@clintoncwolfe Thanks for moving the issue to this repo.

I requested a PR on the current documentation. I'm not sure how to build it though, so I used a mix of GitHub rendering + custom rendering on my machine to check the final output...

**Comment by skpaterson** [comment]
Closing as resolved by #140.
