### ISSUE TITLE
Not able verify the Application Load balancer using aws_alb 

### ISSUE THREAD

**Issue by kvrmanoj** [inspec/inspec-aws#139]
describe aws_alb('arn:aws:elasticloadbalancing') do
  it { should exist }
end

Got the below error while testing the application load balancer using above code.
 
load_with_context'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/dsl.rb:50:in `method_missing': undefined method `aws_alb' for #<#<Class:0x0000000003d210d8>:0x0000000003d20728> (NoMethodError)

**Comment by robh-wirehive** [comment]
I've done the following to dynamically get the list of all the ELBv2's and then do something on each one 

`control 'ELBv2CrossAZ-Networking' do
    impact 1.0
    title 'Check that elbv2 are setup for HA'
    tag 'aws', 'elbv2','HA','networking'

    require 'aws-sdk-elasticloadbalancingv2'

    @region = some-region 

    #get the list of elbv2
    @elbv2Client = Aws::ElasticLoadBalancingV2::Client.new(region: @region)

    @elbListResp = @elbv2Client.describe_load_balancers()

    @elbListResp[:load_balancers].each do |elbv2|

        @elbV2ARN=elbv2[:load_balancer_arn]

        describe aws_alb(load_balancer_arn: @elbV2ARN ) do
            its('some_item')  { should be > X }
        end
    end
end`

**Comment by SowDeu** [comment]
Hi , when I run 
describe aws_alb('arn:aws:elasticloadbalancing') do
it { should exist }
end
I am getting below error: 
undefined method `aws_alb' for #<#<Class:0x000055c6021c6128>:0x000055c6021c5778> (NoMethodError)

**Comment by omer-chefio** [comment]
Hi @SowDeu, 
As this is resolved here #169. I am going to close this issue.
