### ISSUE TITLE
Inspec Profile Throwing Undefined method error while validating "Aws_Auto_Scaling_group"

### ISSUE THREAD

**Issue by kvrmanoj** [inspec/inspec-aws#151]
am using below script to validate the aws auto scaling group.

Inspec version -  4.18

describe aws_auto_scaling_group(name:Auto_Scaling) do
 it { should exist }
 its('min_size') { should be 1}
 its('max_size') { should be 4}
 its('desired_capacity') { should be 2}
end

WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_ecs_cluster' (used at qatest/controls/vpc_exist.rb:1)
[2019-11-12T12:12:59+00:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_security_group' (used at qatest/controls/vpc_exist.rb:9)
Traceback (most recent call last):
        19: from /usr/bin/inspec:150:in `<main>'
        18: from /usr/bin/inspec:150:in `load'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/cli.rb:269:in `exec'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:121:in `run'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:93:in `load'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:93:in `each'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/runner.rb:110:in `block in load'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/profile.rb:200:in `collect_tests'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/profile.rb:200:in `each'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/profile.rb:203:in `block in collect_tests'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/profile_context.rb:147:in `load_control_file'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/profile_context.rb:163:in `load_with_context'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/profile_context.rb:163:in `instance_eval'
         1: from qatest/controls/vpc_exist.rb:21:in `load_with_context'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/dsl.rb:50:in `method_missing': undefined method `aws_auto_scaling_group' for #<#<Class:0x00000000044dfa68>:0x00000000044df1a8> (NoMethodError)
Did you mean?  aws_security_group

**Comment by vsuzdaltsev** [comment]
add 
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.4.tar.gz
```
to profile's inspec.yml

**Comment by omer-chefio** [comment]
Thanks for the support @vsuzdaltsev .
@kvrmanoj , can you update the `inspec.yml` something similar to the following and try again?
```name: InSpec AWS Sample Profile
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  - platform: aws
```

**Comment by omerdemirok** [comment]
@kvrmanoj, please feel free to reopen if this is still a problem.
