### ISSUE TITLE
aws_iam_policy(policy_name: 'NonExistantPolicy') reports "undefined method `arn' for nil:NilClass"

### ISSUE THREAD

**Issue by tenwit** [inspec/inspec-aws#154]
I am seeing an "undefined method" error in the InSpec output when checking for a policy that doesn't yet exist. Checking for a role or user that doesn't exist produces valid failing checks, I expect it to work the same for policies.

MCVE:

```
control "policy-exists" do
  title 'Policy exists.'
  describe aws_iam_policy(policy_name: 'PolicyHasntBeenCreatedYet') do
    it { should exist }
  end
end
```

I expect a red failure line in the CLI output, like I get with users:

>   ×  user-exists: User exists. (1 failed)
>      ×  AWS IAM User  should exist

Instead I get a grey line like this:

>  ↺  policy-exists: Policy exists.
>     ↺  undefined method `arn' for nil:NilClass

If I use `policy_arn` instead of `policy_name`, I get a similar failure. If I use no named parameter (which the docs say should be equivalent to using `policy_name`), I get a useful failure:

> policy-exists: Policy exists.
>      ×  Control Source Code Error /share/modules/policies/controls/iamPolicy.rb:3
>      aws_iam_policy: One of `[:policy_arn, :policy_name]` must be provided.

**Comment by tenwit** [comment]
Awesome thank you, TDD may now proceed, I shall go forth and create policies in AWS!

**Comment by ashima15448** [comment]
I am facing the same error.
Can you please tell me which inspec version I should refer so that this issue doesn't  come?
Currenlty I am using the following inspec profile:

> name: iam-inspec-profile
title: Inspec profile for IAM resource
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/inspec-4.6.9.tar.gz
supports:
  - platform: aws

**Comment by rmoles** [comment]
Hi, @ashima15448 it looks as though the issue may be with the URL you are using for the inspec-aws resource pack. Please select a release version from here:
https://github.com/inspec/inspec-aws/tags
eg.
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.28.0.tar.gz

supports:
  - platform: aws
```

**Comment by ashima15448** [comment]
Thank you @rmoles. My problem is solved now.
