### ISSUE TITLE
Doc and implementation of "aws_iam_policy" differ: missing methods.

### ISSUE THREAD

**Issue by tenwit** [inspec/inspec-aws#157]
# Describe the problem

According to [the documentation](https://www.inspec.io/docs/reference/resources/aws_iam_policy/), the object returned by `aws_iam_policy` provides the `be_attached_to_user` and `be_attached_to_role` methods.  The methods do not exist, and there are no tests for them.

```
     ×  AWS Iam Policy MyPolicy should be attached to user "MyUser"
     expected AWS Iam Policy MyPolicy to respond to `attached_to_user?`
     ×  AWS Iam Policy MyPolicy should be attached to role "MyRole"
     expected AWS Iam Policy MyPolicy to respond to `attached_to_role?`
```

## Possible Solution

The relevant documentation could be removed, or the missing methods and tests could be added. The same methods would not add any new features, since the same check can be done via `aws_iam_user.attached_policy_arns` and `aws_iam_role.attached_policies_arns`.

(FYI: property names differ, note _policy_ vs. _policies_ above.)

**Comment by rgevaert** [comment]
I was bitten by this too
