### ISSUE TITLE
dependency on inspec-bin should be optional, use of cinc-auditor-bin possible

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec-aws#166]
The dependency to inspec-bin requires accepting Chef license. The community built cinc-auditor-bin should be a viable option for use of inspec-azure.
## Detailed Description

Cinc-auditor-bin gem should be an option to inspec-bin.
## Context

Users who want to build on top of OSS without accepting Chef license, cannot use Inspec-bin.
## Possible Implementation

Use `install_if` in Gemfile for inspec-bin/cinc-auditor-bin.
https://bundler.io/v1.10/man/gemfile.5.html#INSTALL_IF-install_if-

**Comment by tbugfinder** [comment]
https://github.com/inspec/inspec-azure/issues/228
https://github.com/inspec/inspec-gcp/issues/224

**Comment by tbugfinder** [comment]
I'm wondering if installing `inspec-bin` is fine if it is not used while not having a Chef license.
Accepting Chef license is asked for after executing `inspec`.


Should `inspec-bin` or `cinc-auditor-bin` installation be dependent on an environment variable like `USE_CINC=YES`?
```
...
if ENV["USE_CINC"] == "YES"
  gem 'cinc-auditor-bin'
else
  gem 'inspec-bin'
end
...
```

**Comment by skpaterson** [comment]
Thanks for this suggestion. However, similarly to InSpec itself, the AWS, GCP and Azure cloud resource packs are Open Source so you are free to fork and update the Gemfile according to your needs. I'll close this out for now.

**Comment by tbugfinder** [comment]
Hi @skpaterson 
couldn't we discuss here a community approach instead of going for the least path which is a fork?
The licensing "restrictions" of inspec-bin shouldn't apply to other projects out-of-the box. Inspec as another Chef project itself doesn't have the dependency to inspec-bin.
Therefore I'm asking for a discussion on how to resolve this lock without creating a fork.

**Comment by tbugfinder** [comment]
I searched the code base for executions of `inspec-bin`and didn't find anything apart of the documentation. Therefore I think this should really be removed.
https://github.com/inspec/inspec-aws/blob/master/Gemfile#L33

**Comment by bobchaos** [comment]
The bin was separated from the core gem so we could use the gem in projects like kitchen-inspec and kitchen-terraform without having to fork and publish a new one. If the resource packs force us down that path, we lose all that value the second we include one.

**Comment by skpaterson** [comment]
Hey folks, the Gemfile for the resource pack is primarily intended for development of the resource pack.  For example, one would typically first install InSpec then depend on the resource pack via `inspec.yml` as documented here: 
https://github.com/inspec/inspec-aws#use-the-resources
The Gemfile inside the resource pack is never used to determine the dependencies in practice - these come via train and the train plugin ecosystem (train-aws for inspec-aws).

**Comment by bobchaos** [comment]
If I'm being perfectly honest I was just reacting to things said in Slack. I'll take some time to do my homework on this and if needed open tickets/PRs in the right places. Thanks for your feedback!
