### ISSUE TITLE
Some AWS Resources methods are throwing unidentified method.

### ISSUE THREAD

**Issue by SowDeu** [inspec/inspec-aws#170]
List of some aws resources are not working as expected like Autoscaling , ECR, ALB, Region, ecs_clusters...

```
title:'auto_scaling_group'
describe aws_auto_scaling_group('MyAutoScalingGroup') do
    it              { should exist }
 end
```

# Describe the problem
AWS Resources :
autoscaling , ecr , region, alb etc .. are giving same kind of error ....

```
from asg.rb:3:in `load_with_context'
 1: from /usr/local/bundle/gems/inspec-4.18.59/lib/inspec/dsl.rb:68:in `method_missing'
/usr/local/bundle/gems/inspec-4.18.59/lib/inspec/dsl.rb:71:in `rescue in method_missing': undefined method `aws_auto_scaling_group' for #<Inspec::ControlEvalContext:0x0000556d6195cdf0> (NoMethodError)
```

Not sure why we are getting above error .Other methods like ecs_cluster , ec2_instance , vpc, elb etc.. are working as expected...

Please help me undertsand is the issue from our end or is there a problem with resource itself..Thanks..

**Comment by clintoncwolfe** [comment]
Hello! I am sorry you are still having trouble. All of the resources you list exist only in the inspec-aws resource pack, and so you would get those errors if you wrote a profile but did not add a dependency on the inspec-aws profile. As I [suggested](https://github.com/inspec/inspec/issues/4839#issuecomment-575297935) in the issue you raised on inspec/inspec yesterday, you must create a profile that depends on the inspec-aws profile. Have you done this?

For details on how to setup a dependency, see the [documentation](https://www.inspec.io/docs/reference/profiles/#profile-dependencies).

**Comment by SowDeu** [comment]
Thank you very much for reply.

I have created the profile but I will cross verify for sure ..  please correct me if I am wrong .. is aws ecr, aws_vpc , aws_ ecs_cluster are working as expected unlike others ... are they all not part of same resource pack ... if there is something wrong with profile will half the resources work and other half won’t work ???? Please help me understand .. I am new to inspec .. Thank you for your time .

**Comment by SowDeu** [comment]
name: Inspec_aws_auto_scaling_group
title: InSpec AUTO_SCALING_GROUP
license: Apache-2.0
summary: An InSpec Compliance Profile for testing AWS AUTO_SCALING_GROUP instances
version: 0.0.1
inspec_version: '>=4.6.9'
depends:
- name: inspec-aws
  url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
- platform: aws

Control : 

control "ASG_name_exists" do
  describe aws_auto_scaling_group('MyAutoScalingGroup') do
    it  { should exist }
  end
end

Error:
 ×  auto_scaling_group exists: verify/controls/auto_scaling_group.rb:19
     ×  Control Source Code Error verify/controls/auto_scaling_group.rb:19 
     undefined method `aws_auto_scaling_group' for #<Inspec::Rule:0x0000564afb32f450>

Please Help me understand what is that I am doing wrong.

**Comment by SowDeu** [comment]
Got its, Its inspec lock which was giving issue.
