### ISSUE TITLE
Undefined method when executing aws_eks_clusters test

### ISSUE THREAD

**Issue by rbizzell40** [inspec/inspec-aws#172]
#  Describe the problem
I am running inspec 4.18.51 with Ruby version 2.60 and the other test I am running I haven't seen this error. I an trying to execute a simple aws eks cluster test to verify my cluster and the move on to more comprehensive test.
describe aws_eks_clusters do
  its('names') { should include('cluster-1') }
end

`method_missing'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/dsl.rb:71:in `rescue in method_missing': undefined method `impact' for #<#<Class:0x00007fbcdc39cc90>:0x00007fbcdc39c128> (NoMeth# Possible Solution

I tried the test on a totally different machine and got the same error.
I am pretty new to inspec as well. This is something basic.

**Comment by rmoles** [comment]
Hi @rbizzell40, thanks for raising an issue. Would you be able to provide an example of the inspec.yml and full control?

**Comment by rbizzell40** [comment]
Sure thing

**Comment by rbizzell40** [comment]
name: uchi
title: AWS InSpec Profile
maintainer: uchi
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '>=4.6.9'
depends:
  - name: inspec-aws
    url:  https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  - platform: aws

describe aws_eks_clusters do
  its('names') { should include('inspec') }
end

**Comment by rbizzell40** [comment]
It was formatting error.
