### ISSUE TITLE
vpc doesn't support tags although documented

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec-aws#173]
Looking at #69, `tags` should have been added to `aws_vpc`. It _is_ added to `aws_vpcs` but there's nothing that I can see directly or via metaprogramming that seems to plug this in.

See https://chefcommunity.slack.com/archives/C1XB6U6MN/p1579798584003800 for more.

**Comment by vsuzdaltsev** [comment]
works for me with
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.3.tar.gz
```
```
inspec> aws_vpc(:vpc_id=>"vpc-0db.................").tags
=> {"Network"=>"Public", "Billing"=>"test", "Name"=>"test-vpc_eks", "Application"=>"test", "Stack-Name"=>"test"}
```

**Comment by vsuzdaltsev** [comment]
@zenspider ?

**Comment by skpaterson** [comment]
This appears to be working as documented (thanks for confirming @vsuzdaltsev) https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_vpc.md#test-tags-on-the-vpc so will close out this issue for now.
