### ISSUE TITLE
Auto_scaling_group- Name parameter not working

### ISSUE THREAD

**Issue by sesha27** [inspec/inspec-aws#187]
Resource Auto_scaling_group( 'TestGroupName') doesn't work as expected.
Note : 4 Weeks back same code did run without any issues.

# Describe the problem
YAML FILE:
inspec_version: '>=4.6.9'
depends:
- name: inspec-aws
  url: https://github.com/inspec/inspec-aws/archive/master.tar.gz

Test: 
control 'aws-auto-scaling-group_exists' do
  describe aws_auto_scaling_group('TestGroupName') do
   it { should exist }
  end
end

Actual Result:
 ×  aws-auto-scaling-group_exists: AWS Auto Scaling Group 
     ×  AWS Auto Scaling Group  is expected to exist
     expected AWS Auto Scaling Group  to exist

Expected Result: Something like below
 ✔   aws-auto-scaling-group_exists: AWS Auto Scaling Group: TestGroupName
     ✔  AWS Auto Scaling Group: TestGroupName is expected to exist

**Comment by sesha27** [comment]
Please help : we are impeded in implementing tests at our work place..

**Comment by rmoles** [comment]
Hi, @sesha27 thanks for submitting the issue. I am going to attempt to replicate this issue. One thing I have noticed about your setup is that in the inspec.yml you are depending on master. We would advise to pin to a specific release of the resource pack. Release versions can be found here: https://github.com/inspec/inspec-aws/releases

**Comment by sesha27** [comment]
@rmoles : Thank you , I will update my yml file according to your suggestion . Please keep me informed if you were able to replicate the issue

**Comment by sesha27** [comment]
@rmole : Inspec version - 4.18.59

**Comment by rmoles** [comment]
@sesha27  Thanks for checking that. I'm in the process of trying to replicate this issue within our build. I see that there is a newer version of inspec available ` 4.18.100` would you be able to update to the latest version and run `inspec vendor <profile> --overwrite` and then retry the control?

**Comment by sesha27** [comment]
@rmoles  : I will give it a try and update..Thanks

**Comment by rmoles** [comment]
Hi @sesha27, unfortunately, I haven't been able to reproduce this issue. I have tested using the following:
test-
```
  title 'Ensure AWS Auto Scaling Group has the correct properties.'

  describe aws_auto_scaling_group(auto_scaling_group_name: group_name) do
    it           { should exist }
    its ('name') { should eq group_name}
  end
```

inspec.yml-
```
version: 0.1.0
license: Apache-2.0
inspec_version: '>= 3.0.25'
depends:
  - name: inspec-aws
     url: https://github.com/inspec/inspec-aws/archive/v1.6.10.tar.gz
```

inspec version-
```
inspec --version
4.18.100
```

result-
```
✔  aws-auto-scaling-group-1.0: Ensure AWS Auto Scaling Group has the correct properties.
     ✔  AWS Auto Scaling Group aws-auto-scaling-group is expected to exist
     ✔  AWS Auto Scaling Group aws-auto-scaling-group-ipmwvamknjszaisgrzuwrmnzr name is expected to eq "aws-auto-scaling-group"
```

**Comment by rmoles** [comment]
@sesha27 would you be able to verify using the aws cli tool that the scaling group exists?
```
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name <your-aws-auto-scaling-group>
```

**Comment by sesha27** [comment]
@rmoles: Thank you very much .. Issue is from our end .. Autoscaling group name has been changed apparently and we weren't aware of that change which created this much communication.  Apologies I should have tested with different set of values before creating an issue.
