### ISSUE TITLE
Inspec AWS Assume Role Documentation

### ISSUE THREAD

**Issue by damacus** [inspec/inspec-aws#19]
### 🎛 Description

🙋 feature request

It's not clear how to run Inspe against multiple AWS accounts with different profiles. 

As discussed with @chris-rock at the Summit, a common pattern in AWS is to use a central `identity` account to assume roles into another account. 

There's no clear way to do this in Inspec

### Related

- AWS Credentials don't error out when AWS profile has no credentials/access (sorry can't find related ticket!)

### 🌍 InSpec and Platform Version

- v3.0.0
- Documentation
- AWS

### 🤔 Replication Case

- Setup two accounts
- `account_a` has users with permissions to assume role into `account_b`
- `account_b` has resources we want to test.
- `account_b` has no users
- `account_b` has a role which is assumable by a specific user in `account_a`

### 💁 Possible Solutions

- Clearer documentation about using `~/aws/config` & `~/.aws/credentials`
- Allow a `assume_role_arn` to be set on the cli to indicate the which account we want to access.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by skpaterson** [comment]
Extend existing documentation to include `assume_role_arn` usage.

**Comment by rmoles** [comment]
This issue has been addressed in recent changes to the README.
https://github.com/inspec/inspec-aws/blob/master/README.md
```
The credentials precedence is:

Credentials set in .envrc OR as an Environment variable.
Credentials set in ~/.aws/credentials AND ~/.aws/config AND AWS_PROFILE set in as an Environment variable.
Credentials set in ~/.aws/credentials AND ~/.aws/config AND AWS_PROFILE variable is NOT set in .envrc. Default credentials will be used.
```
