### ISSUE TITLE
clarification on "Project State: Maintained"

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec-aws#196]
### 🎛 Description

This is a question about the project state.
I'm wondering why this isn't an active project like InSpec itself but "Project State: Maintained". As per my understanding inspec-aws will replace all aws resources for InSpec.

### 💁 Possible Solutions

This repo should have an active state setting.

**Comment by skpaterson** [comment]
Hi @tbugfinder - thanks for the query.  Based on our internal priorities, the current project state is "Maintained".  However, this may change to "Active" in the not too distant future.  Either way, the README will always reflect the current project state according to - https://github.com/chef/chef-oss-practices/blob/master/repo-management/repo-states.md 
I hope this answers your question and will close this out for now.
