### ISSUE TITLE
version 1.10 has missing file aws-sdk-efs

### ISSUE THREAD

**Issue by akacodemonkey** [inspec/inspec-aws#203]
Version 1.10.0 fails to load as it is missing file aws-sdk-efs

Traceback (most recent call last):
        30: from /usr/local/bundle/bin/inspec:23:in `<main>'
        29: from /usr/local/bundle/bin/inspec:23:in `load'
        28: from /usr/local/bundle/gems/inspec-bin-4.16.0/bin/inspec:11:in `<top (required)>'
        27: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/base_cli.rb:33:in `start'
        26: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        25: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        24: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/cli.rb:293:in `exec'
        21: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/runner.rb:122:in `run'
        20: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/runner.rb:94:in `load'
        19: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/runner.rb:94:in `each'
        18: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/runner.rb:100:in `block in load'
        17: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile.rb:247:in `load_libraries'
        16: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile.rb:247:in `each_with_index'
        15: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile.rb:247:in `each'
        14: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile.rb:262:in `block in load_libraries'
        13: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile.rb:270:in `load_libraries'
        12: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile_context.rb:134:in `load_libraries'
        11: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile_context.rb:134:in `each'
        10: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile_context.rb:137:in `block in load_libraries'
         9: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile_context.rb:150:in `load_library_file'
         8: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile_context.rb:161:in `load_with_context'
         7: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/profile_context.rb:161:in `instance_eval'
         6: from libraries/aws_alb.rb:3:in `load_with_context'
         5: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/dsl_shared.rb:26:in `require'
         4: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/dsl_shared.rb:26:in `eval'
         3: from libraries/aws_backend.rb:27:in `create'
         2: from /usr/local/bundle/gems/inspec-4.16.0/lib/inspec/dsl_shared.rb:13:in `require'
         1: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk-efs (LoadError)

# Describe the problem
Rather than executing the tests we have developed, inspec fails with file not found.  Work around at the moment is to revert to 1.9

**Comment by omer-chefio** [comment]
Thanks for raising this issue. This appears to be a duplicate of #202. This should hopefully resolve your issue.

**Comment by akacodemonkey** [comment]
cheers, did look prior to raising the issue and missed this.  Will close ta
