### ISSUE TITLE
aws_iam_policy have_statement should support 'Action' being a list as in the documentation

### ISSUE THREAD

**Issue by skpaterson** [inspec/inspec-aws#225]
For example, the below should match if all are present in the policy:
```
it { should have_statement(Sid: '',
                Resource: 'arn:aws:kms:eu-west-2:123893415416:key/123456-8daa-4f9e-962f-2342h5lk23j4h',
                Effect: 'Allow',
                Action: ['kms:ListKeys', 'kms:ListAliases', 'kms:GenerateDataKey', 'kms:Encrypt', 'kms:Describe*', 'kms:Decrypt'])}
```

The current workaround is to have a statement for each item in the list separately e.g. 

```
     it { should have_statement(Resource: 'arn:aws:kms:eu-west-2:123893415416:key/123456-8daa-4f9e-962f-2342h5lk23j4h',
                               Effect: 'Allow',
                               Action: 'kms:ListKeys')}
     it { should have_statement(Resource: 'arn:aws:kms:eu-west-2:123893415416:key/123456-8daa-4f9e-962f-2342h5lk23j4h',
                               Effect: 'Allow',
                               Action: 'kms:ListAliases')}
```

**Comment by rmoles** [comment]
This may be related to #192

**Comment by omerdemirok** [comment]
When a criteria is passed to the `has_statement` with an empty string value, like `Sid: ""`, should we pass if there is a statement:
- with or without a `Sid` element, regardless of the value
or
- with a `Sid` element defined and it equals to empty string `""`

**Comment by rmoles** [comment]
> When a criteria is passed to the `has_statement` with an empty string value, like `Sid: ""`, should we pass if there is a statement:
> 
> * with or without a `Sid` element, regardless of the value
>   or
> * with a `Sid` element defined and it equals to empty string `""`

I would imagine that it would match Sid with an empty string. Also, could be wrong, but I'm not sure there is a scenario where Sid isn't present in the response.

**Comment by omerdemirok** [comment]
`Sid` is an [optional](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html) element in statements. 
However, AWS still returns its value `""` even it is defined like that.  
I believe if it is empty we should just ignore the criteria, but on the other hand, leaving this decision to the users might be more consistent with API behavior.
Thanks @rmoles
