### ISSUE TITLE
Adding logging types into aws_eks_clusters

### ISSUE THREAD

**Issue by voojoe** [inspec/inspec-aws#240]
## Detailed Description
This would add two additional attributes to aws_eks_cluster, enabled_logging_types and disabled_logging_types. These would both return a list of the types of logging that have been enabled/disabled in AWS.

## Context
This could be used to check the logging status of an EKS cluster and identify which types have been enabled/disabled.

## Possible Implementation
I've developed this locally so I'll create a branch with the proposed changes.

**Comment by omerdemirok** [comment]
Thanks for this contribution @voojoe!
