### ISSUE TITLE
Issue in using aws_cloudwatch_log_metric_filter

### ISSUE THREAD

**Issue by ashima15448** [inspec/inspec-aws#244]
I am trying to use the aws_cloudwatch_log_metric_filter resource on my AWS instance. However, I am getting the following error on my Linux instance. 
![image](https://user-images.githubusercontent.com/32170935/89650455-1718da00-d8e0-11ea-8ef8-c7bdec48bcc9.png)

Following is the file where it is showing error:
![image](https://user-images.githubusercontent.com/32170935/89617622-2a0fb800-d8a8-11ea-8a5a-6685a9f751da.png)
I have understood that the variable message does not contain a string. However, I am unable to understand how to solve it. I have not made any changes to the default file.

**Comment by omerdemirok** [comment]
Hi @ashima15448, seems like you are using an AWS resource from InSpec core. They are being deprecated.

Can you share the content of the `inspec.yml` used, and see [here](https://github.com/inspec/inspec-aws#use-the-resources) for an example `inspec.yml` pointing to the AWS resource pack.

**Comment by ashima15448** [comment]
Hi @omerdemirok, 

As you can see in the following image, I am using the same inspec.yml specified in the link you have shared.

![image](https://user-images.githubusercontent.com/32170935/89644924-707c0b80-d8d6-11ea-95cc-be0348185f41.png)

Output=>
![image](https://user-images.githubusercontent.com/32170935/89645257-057f0480-d8d7-11ea-9b76-fe63d627a73f.png)

I am able to use other AWS resources like aws_ec2_instance and aws_iam_user but facing issue with resources related to cloudwatch. For you reference, I have given full access for cloudwatch to my AWS user.

Thank you.

**Comment by ashima15448** [comment]
For reference, 

The first problem I faced was 
![image](https://user-images.githubusercontent.com/32170935/89645999-91456080-d8d8-11ea-9de8-1776e1d78d32.png)

for which I added a .to_s function in line 861 
![image](https://user-images.githubusercontent.com/32170935/89646069-acb06b80-d8d8-11ea-8a8c-af54bad82cb3.png)

**Comment by ashima15448** [comment]
Hi @omerdemirok,

I have used the same inspec.yml file you have attached in the mail:

![image](https://user-images.githubusercontent.com/32170935/89652162-b048f000-d8e2-11ea-819c-04d334c67b0d.png)

for which the output I am getting now is:

![image](https://user-images.githubusercontent.com/32170935/89652224-cb1b6480-d8e2-11ea-9e80-b3174050f9c3.png)

**Comment by omerdemirok** [comment]
@ashima15448, can you delete the `inspec.lock` file next to `inspec.yml` and try again?

**Comment by ashima15448** [comment]
The profile is no longer running after removing inspec.lock file.

The following error is getting displayed:

> Profile URL dependency https://github.com/inspec/inspec-aws/archive/x.tar.gz could not be fetched: 404 Not Found

**Comment by omerdemirok** [comment]
Please try this: https://github.com/inspec/inspec-aws/archive/v1.27.0.tar.gz
(replace `x` with a release version)
```
name: my-profile
title: My own AWS profile
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.27.0.tar.gz
supports:
  - platform: aws
```

**Comment by ashima15448** [comment]
Thank you so much @omerdemirok. This has solved the issue.
