### ISSUE TITLE
content_length property not being identified in aws_s3_bucket_object

### ISSUE THREAD

**Issue by ashima15448** [inspec/inspec-aws#249]
Hi,

I am using the following code in my file as described in the documentation:

    
    #   Test an object’s size in bytes is less than 100000 
    describe aws_s3_bucket_object(bucket_name: bucket_name, key: 'test.txt') do
        its('content_length') { should be < 1_000_000 }
      end   

    #   Test an object’s type is “image/jpeg”
    describe aws_s3_bucket_object(bucket_name: bucket_name, key: 'sample.JPG') do
    its('content_type') { should eq "image/jpeg" }
    end`

However I am getting error while executing it:
 `undefined method content_length for #<#<Class:<....>:<....>`
 ` undefined method content_type for #<#<Class:<....>:<....>`

For reference, I am using the following inspec.yml:

> name: vpc-inspec-profile
> title: Inspec profile for s3 resource
> version: 0.1.0
> inspec_version: '>= 4.6.9'
> depends:
>   - name: inspec-aws
>     url: https://github.com/inspec/inspec-aws/archive/inspec-4.6.9.tar.gz
> supports:
>   - platform: aws

**Comment by omerdemirok** [comment]
@ashima15448, can you delete existing `inspec.lock` file and update the `inspec.yml` as described [here](https://github.com/inspec/inspec-aws/issues/154#issuecomment-677679562).

**Comment by rmoles** [comment]
I believe that this and #250 can probably be closed as it looks like they're all down to the incorrect URL. I would just like confirmation from @ashima15448 before we close.

**Comment by ashima15448** [comment]
Yes, you can close the issue. I had used the oldest version available so many features would not be in it. Hence I was facing the problem. Thank you so much for your help.
