### ISSUE TITLE
allow us to find resource names using regex

### ISSUE THREAD

**Issue by kidbrax** [inspec/inspec-aws#289]
## Detailed Description
I'd like to be able to find a resource using a regex for the name. 

## Context
It is good practice to not hardcode names of resources in AWS since this often requires that resource to be completely rebuilt upon changes instead of just being updated. So AWS generates names dynamically with a suffix. Without this, we cannot test these resources which makes the tool extremely limited to the point where it's not worth using at all.

## Possible Implementation
```
describe aws_iam_role(role_name: /some-resource-name-*/) do
    it { should exist }
end
```

**Comment by omerdemirok** [comment]
@kidbrax, thanks for opening this issue.
The InSpec AWS cloud resource pack resources are limited by the Ruby AWS SDK. For the iam_roles, a lookup by using a regex is not supported by the SDK. See here: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/IAM/Client.html#get_role-instance_method

However, what you are after can be achieved by using the plural InSpec resources. See the following example:

```
describe aws_iam_roles.where { role_name.start_with?('some-resource-name-') } do
  it { should exist }
  its('count') { should be 3 }
end
```

You can refer here for more on the plural resource filtering: https://github.com/inspec/inspec/blob/master/dev-docs/filtertable-usage.md#a-where-method-you-can-call-with-hash-params-with-loose-matching

I hope this resolves this issue.

**Comment by kidbrax** [comment]
Thank you, this works!
