### ISSUE TITLE
AWS Resource: Nat Gateway

### ISSUE THREAD

**Issue by jseiser** [inspec/inspec-aws#31]
### 🎛 Description

**🙋 feature request?

Would like a aws_nat_gateway and aws_nat_gateways resource.

### 💁 Possible Solutions

```
describe aws_nat_gateway(nat-gateway-id: nat-1da12de71e7fee8db) do
  it { should exist }
end

describe aws_nat_gateway.where(vpc_id: vpc-123456 ) do
  its('count') { should eq 2 }
  its('statee) { should cmp ' }
end
```

Properties would be, vpc_id, nat-gateway-id and state.

**Comment by krystan** [comment]
I could have a stab at this
