### ISSUE TITLE
AWS RDS DBSubnetGroup Support

### ISSUE THREAD

**Issue by ppradhan9** [inspec/inspec-aws#331]

**Comment by soumyo13** [comment]
This resource already there in the github repo. there is no need of rewriting this.

**Comment by soumyo13** [comment]
https://github.com/inspec/inspec-aws/pull/221 This is the PR link

**Comment by ppradhan9** [comment]
The PR is already closed. @sathish-progress please don't test it on terraform.
Closing this issue
