### ISSUE TITLE
Create a common interface for AWS tag queries

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-aws#34]
### 🎛 Description

🙋 feature request

This issue supercedes #2592, which had a lot of other discussion.  Refs #3138 

Most AWS resources support tagging - attaching a (sometimes limited) number of key-value pairs.  We'd like to expose this to users in several ways.

Unfortunately, the API for fetching tags varies widely by services, so each resource will need to implement the actual fetch, while a shared library might be able to handle the properties / matchers /filter criteria definitions.

Thoughts on desired behavior:

#### Singular resources

* `tags` property returning a hash

Already implemented by aws_ec2_instance, PR for `aws_s3_bucket` on #3138 

* `has_tag?(tag_name)` matcher

* `has_tag_value?(tag_name, tag_value)` matcher

#### Plural resources

* `tags` merged hash property. Are values boosted to arrays?

* has_tag(tag_name) filter_criteria

* has_tag_value(tag_name, tag_value) block-only filter_criteria

#### Dynamic properties?

Azure also defines custom properties, based on the observed tags: `name_tag`, `env_tag`, etc.  Is that desirable?  How do you handle absence?  Is that possible to implement as filter criteria on a plural?

#### Case sensitivity?

AWS tags are sometimes titlecased (Name is, traditionally).

### 🌍 InSpec and Platform Version

2.2.10

**Comment by dmurray-chef** [comment]
Taking a different approach to this

**Comment by steveparker-1984** [comment]
Could you possibly share your thoughts on this? It would be extremely useful for us to have a means to check tag presence, without knowing the value.

**Comment by anthonycolon25** [comment]
Hi,

Is there an ETA for this functionality?

I also wanted to add a few potential use cases (some of these are listed above):
- Being able to check that a resource that supports tags has tags assigned.  I guess it could check if a tags list is empty or not
- Being able to check if a resource that supports tags has a specific "required" tag assigned to it (e.g. business_unit) and that the value matches a specific regex (e.g. ^(bu1|bu2)$ )
- Being able to check if an "optional" tag exists, if it does then check it's value against a regex. If not skip the test.
