### ISSUE TITLE
Route53 Record

### ISSUE THREAD

**Issue by eteterra-agworld** [inspec/inspec-aws#352]
I'd like to verify that a particular zone (lets say acme.com.) has a particular CNAME record attached, eg (us-billing.dev.acme.com)

## Detailed Description
using `aws route53 list-resource-record-sets ..` I can see the record is listed, so the information is presumably available.

## Context
I'd use it to verify that the CNAME records I depend on that are created through terraform are really there, even after a change.

## Possible Implementation
If given some pointers where to start i'd be happy to have a go at writing some code

**Comment by sathish-progress** [comment]
I guess this is already possible. Please find the documentation here https://docs.chef.io/inspec/resources/aws_hosted_zone/#syntax

**Comment by eteterra-agworld** [comment]
I had another look and you're right it, `record_names` does work for this use case already :) thanks a bunch!
