### ISSUE TITLE
hosted_zone missing records

### ISSUE THREAD

**Issue by eteterra-agworld** [inspec/inspec-aws#356]
I'd like to use aws_hosted_zone to check the records i've configured.

# Describe the problem
- my hosted zone has a total of 621 records
- when I check the contents of `aws_hosted_zone('acme.com.').record_names`, I only see 110 records being returned
- when i try to test using eg `its('record_names') { should include "us-billing.acme.com." }` it doesn't find the record, even though it's there when i check in the aws console
- i would expect the hosted_zone(..).record_names size to equal 621, same as what I see in the aws console

## Possible Solution
I would be happy to write some code if someone could get me started on where to look :)

**Comment by eteterra-agworld** [comment]
digging into it a bit, from the aws route53 client, method `list_hosted_zones` docstring: 

... Route 53 returns up to 100 items in each response.

so the issue is at `libraries/aws_hosted_zones.rb` line 27: `resp =@aws.route53_client.list_hosted_zones`.
we'd have to check the responses `isTruncated` value and use the marker provided to keep making requests until we have fetched all the data.

**Comment by Williambrailey** [comment]
I am having a similar issue but its on a host with only 60 records, its only returning about 30 of them but the ones its not returning all have alias targets. 
This might just be my error as have only just started using Inspec but thought I would flag it up just incase its helpful.

**Comment by ashokmnr** [comment]
I am having a similar issue with ``` hosted_zone_id ```.  It's only returning 4 record sets for me.

**Comment by rdanilin** [comment]
Same here. Any plans to fix this issue?

**Comment by Nirbhay1997** [comment]
Closing as fixed

**Comment by rdanilin** [comment]
@Nirbhay1997 seems like the issue was not fixed. 
Could we re-open this ticket?

**Comment by mwiczynski-cartera** [comment]
This is not fixed by #811 That PR only changed aws_hosted_zones.  aws_hosted_zone is still broken, not returning all records.
