### ISSUE TITLE
AWS Cloudwatch Alarms cannot be found from Metrics with Dimensions

### ISSUE THREAD

**Issue by Jacob-Laverty** [inspec/inspec-aws#37]
### 🎛 Description

🐛 bug report

Inspec fails to find cloudwatch alarms when the search metric has dimensions associated with it.

### 🌍 InSpec and Platform Version
2.1.0

### 🤔 Replication Case

1. Create a Cloudwatch Metric with at least 1 dimension.
2. Create an alarm on that metric.
3. Create and run a simple inspec test to find your alarm
```
describe aws_cloudwatch_alarm(
  metric_name: "My_Metric_Name_with_dimension",
  metric_namespace: "AWS/ECS",
) do
  it {should exist}
end
```
4. Notice inspec fails to find the alarm

### 💁 Possible Solutions
The issue is that the allowed params for the aws_cloudwatch_alarm resource do not allow the dimension field to be passed to the request. This field is required (if the metric contains dimensions) for the describe_alarms_for_metric method in the AWS SDK.

Here are the allowed params for the inspec resource:

```
recognized_params = check_resource_param_names(
      raw_params: raw_params,
      allowed_params: [:metric_name, :metric_namespace],
    )
```

Here is the example from the AWS ruby SDK for the describe_alarms_for_metric method (the backend for the Inspec Cloudwatch resource):

```
resp = client.describe_alarms_for_metric({
  metric_name: "MetricName", # required
  namespace: "Namespace", # required
  statistic: "SampleCount", # accepts SampleCount, Average, Sum, Minimum, Maximum
  extended_statistic: "ExtendedStatistic",
  dimensions: [
    {
      name: "DimensionName", # required
      value: "DimensionValue", # required
    },
  ],
  period: 1,
  unit: "Seconds", # accepts Seconds, Microseconds, Milliseconds, Bytes, Kilobytes, Megabytes, Gigabytes, Terabytes, Bits, Kilobits, Megabits, Gigabits, Terabits, Percent, Count, Bytes/Second, Kilobytes/Second, Megabytes/Second, Gigabytes/Second, Terabytes/Second, Bits/Second, Kilobits/Second, Megabits/Second, Gigabits/Second, Terabits/Second, Count/Second, None
})
```

Notice that the dimensions field is required for this method. From the documentation:

> :dimensions (Array<Types::Dimension>) — The dimensions associated with the metric. If the metric has any associated dimensions, you must specify them in order for the call to succeed.

To resolve:

1. Add dimensions as an allowed field.
2. Pass that field to the query in the same way that metric name and namespace are being passed.

P.S.

I can open a new issue if you would prefer but for AWS resources specifically, why do we define the allowed params that are used for the request? The AWS SDK already has built in parameter validation so having Inspec define "allowed params" seems more restrictive than helpful. I would think that just passing the params from the user to the AWS SDK and then bubbling invalid param errors would be more robust / resilient than having to field support issues like these. Thanks :)

**Comment by rmoles** [comment]
Addressed by #88
