### ISSUE TITLE
Incorrect docs for ARN resource parameter for aws_iam_policy

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-aws#44]
### 🎛 Description

🐛 bug report

`aws_iam_policy` docs say that you can use an ARN to retrieve a policy, but there is no example of the resource parameter syntax for that. 

In fact, [this](https://github.com/chef/inspec/blob/master/lib/resources/aws/aws_iam_policy.rb#L58) shows that in fact it does not accept ARN.

I suggest that we update it to allow ARN, and also provide an example.

### 🌍 InSpec and Platform Version

2.1.30

### 🤔 Replication Case

Visit [the aws_iam_policy docs](https://www.inspec.io/docs/reference/resources/aws_iam_policy/#syntax)

**Comment by rmoles** [comment]
This issue has been addressed in PR #75
