### ISSUE TITLE
Add managed_by_aws filter to aws_kms_keys

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-aws#45]
### 🎛 Description

🙋 feature request

Add a filter criterion to `aws_kms_keys` (plural) to filter AWS-managed keys from customer-managed keys.

### 🌍 InSpec and Platform Version

2.1.21

### 💁 Possible Solutions

Note that `aws_kms_key` (singular) provides a `managed_by_aws?` matcher.  I think the same name would be best.  And it would likely give hints to implementation.

**Comment by rmoles** [comment]
Issue closed as this information is not returned by the `list_keys` api call. We want to avoid looping over the list of keys and making individual api calls per key.
example of what is returned by the `list_keys` resource in AWS SDK
```
   #   resp.keys #=> Array
    #   resp.keys[0].key_id #=> String
    #   resp.keys[0].key_arn #=> String
    #   resp.next_marker #=> String
    #   resp.truncated #=> Boolean
```
