### ISSUE TITLE
Feature request: new resource aws_ssm_parameter

### ISSUE THREAD

**Issue by salekseev** [inspec/inspec-aws#47]
### 🎛 Description

Feature request: new resource aws_ssm_parameter is neede3d to check the value of SSM parameter by it's path with optional decryption.

### 🌍 InSpec and Platform Version

2.1.0

### 💁 Possible Solutions

Using aws-sdk https://docs.aws.amazon.com/sdkforruby/api/Aws/SSM/Types/GetParametersByPathRequest.html

**Comment by skpaterson** [comment]
We'll explore supporting the new resource as per - https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html

**Comment by soumyo13** [comment]
In the main, already Sam has made the change and it is already there. Please let me know if any more requirement is there.
