### ISSUE TITLE
Feature Request: Add AWS loadbalancer resource to check port, protocol and encryption

### ISSUE THREAD

**Issue by mrcasablr** [inspec/inspec-aws#48]
AWS supports 3 loadbalancers -

ELB Classic - Elastic load balancer
ALB - Application load balancer
NLB - Network loadbalancer

Each load balancer supports  port, protocol. ALB/ELB supports TLS offloading as well. 

This request is to add a inspec resource that allows checking for port, protocol and TLS configuration on the loadbalancer

**Comment by SowDeu** [comment]
Hi , I am working on testing NLB resource on AWS with chef inspec , would like to know if we are able to test it now, if so where about's we can find the document and which version of inspec supports this feature. Inspec - https://www.inspec.io/docs/reference/resources/#aws-resources does not have that resource added . Please help. Thanks in advance.

**Comment by rmoles** [comment]
Hi @SowDeu, it seems the alb resource covers what you are looking for, as it will return all load balancers by name. https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_alb.md
I have added an issue to the backlog to clarify that the NLB and ALB functionality is covered in this resource. https://github.com/inspec/inspec-aws/issues/169

**Comment by SowDeu** [comment]
@rmoles : Thanks for the update.Its quite helpful.
