### ISSUE TITLE
Set a default AWS region when nothing is specified in the environment

### ISSUE THREAD

**Issue by skpaterson** [inspec/inspec-aws#5]
### 🎛 Description

The new AWS InSpec resources are multi-region as required e.g. 
```
  aws_regions.region_names.each do |region|
    aws_security_groups(aws_region: region).group_ids.each do |security_group_id|
      describe aws_security_group(aws_region: region, group_id: security_group_id) do
        it { should_not allow_in(ipv4_range: '0.0.0.0/0', port: 21) }
      end
    end
  end
```
As such, the concept of a 'default region' is less relevant than before.  Currently we end up with lots of errors if no region is explicitly set in the environment.

### 🤔 Replication Case

Run any profile depending on this resource pack without the region set:
```
$ inspec exec my-profile -t aws://
```

### 💁 Possible Solutions

Our current implementation requires `AWS_REGION` to be set but we could now reasonably add a default to `us-east-1`.  This would require copying the SDK region detection and injecting `us-east-1` if nothing is found.

**Comment by skpaterson** [comment]
Ensure region precedence is documented in README.

**Comment by llibicpep** [comment]
@skpaterson I'm not sure the issue reported in https://github.com/inspec/inspec/issues/2717 and this one is the same. Basically here you're saying you'll forcibly set default to `us-east-1` if nothing specified in the environment, but what I was saying in the other ticket is - the profile in `~/.aws/credentials` might have region set already with the creds and you basically going to override what was set there based on no env variable found. It's a source of potential issues... I'm not sure how to read it from creds file - I don't see any API calls available as well as https://github.com/aws/aws-sdk-ruby/issues/1028 being closed. Inspec should not do anything extra if region was already provided - so maybe the simplest way to check it is to perform a simple `sts get-caller-identity` call to see if it succeed without providing a region.

**Comment by skpaterson** [comment]
hi @llibicpep - thanks for calling this out!  The intent here will be to work out if a region is specified anywhere, including in supplied credentials file, and only set the default if nothing is found.

**Comment by rmoles** [comment]
This issue appears to have been fixed by previous changes. The above PR adds documentation surrounding the different methods of setting credentials and region.
