### ISSUE TITLE
Resource aws_rds_clusters Raises Exception When db_cluster_members from aws.rds_client.describe_db_clusters Response Object is Null

### ISSUE THREAD

**Issue by jnikles1** [inspec/inspec-aws#503]
# Describe the problem

When trying to write a control which makes use of the aws_rds_clusters resource, we found that none of our existing clusters were found when calling the resource. The following exception was observed in inspec shell:

``
inspec> @resource_exception_message
=> "undefined method `db_instance_identifier' for nil:NilClass"
``

After further investigation, it appears that the resource tries to get the db_instance_identifier of the 0 index item in the db_cluster_members array. 

![image](https://user-images.githubusercontent.com/61483166/127392644-d9a3bd68-4b63-4e86-8427-56a27a2636f8.png)

Expected behavior:
aws_rds_clusters resource should get all existing rds clusters. The cluster_members variable should get all db_cluster_members when they exist, and not just the 0 index member.

## Possible Solution
Change line 46 of the resource to the following:
cluster_members:                  rds_cluster.db_cluster_members ~~[0].db_instance_identifier~~

This would get all db_cluster_members when they exist, and would not cause the exception to be raised when there are no db_cluster_members

**Comment by trickyearlobe** [comment]
Might also be possible to change it to `rds_cluster.db_cluster_members.map{ |member| member.db_instance_identifier}` if the identifiers are the only thing we need and `rds_cluster.db_cluster_members` always returns an array (albeit an empty one)
