### ISSUE TITLE
aws_cloudfront_distributions origin_path is missing

### ISSUE THREAD

**Issue by sharmajee1** [inspec/inspec-aws#512]
At present `aws_cloudfront_distributions` doesn't provide checks for the `origin_path`

Detailed Description
This is a critical check for `aws_cloudfront_distributions` , to make sure cloudfront distributions has specific `origin_path` or it is empty.

Context
As a part of compliance check `origin_path` is very important. So looking for the same as a compliance check.

Possible Implementation
Just add origin_path method

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginPath

**Comment by ppradhan9** [comment]
pr Merged closing this issue
