### ISSUE TITLE
aws_ec2_security_group does not report the inspected security group name or id

### ISSUE THREAD

**Issue by chef-ci** [inspec/inspec-aws#55]
<a href="https://github.com/aaronlippold"><img src="https://avatars3.githubusercontent.com/u/1486440?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aaronlippold](https://github.com/aaronlippold)**
_Saturday Dec 16, 2017 at 19:08 GMT_
_Originally opened as https://github.com/chef/inspec-aws/issues/143_

----

When you execute a control that uses the `aws_ec2_security_group` resource it should report the name of the security group in all formatters.

```
 ✔  aws_security_group: EC2 Security Group should exist
     ✔  EC2 Security Group should exist
```
should be something like:
```
 ✔  aws_security_group: EC2 Security Group should exist
     ✔  EC2 Security Group `sg-a12345` should exist
```

**Comment by dmurray-chef** [comment]
This looks to have been resolved.
