### ISSUE TITLE
Issue with aws-sdk-waf in v1.74.72 - cannot load such file (LoadError)

### ISSUE THREAD

**Issue by maxlambnc** [inspec/inspec-aws#796]
# Describe the problem

When trying to run with this dependency on inspec (v.4.50.3) , we are encountering an issue where it is unable to load the aws-sdk-waf (which was added in #794 for 1.74.72, this works in 1.74.71):

```
depends:
- name: inspec-aws
  git: https://github.com/inspec/inspec-aws.git
  version: ~> 1.74
supports:
  platform: aws
```

Error and stack trace:

```
+ inspec exec tests --no-create-lockfile -t aws://
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- aws-sdk-waf (LoadError)
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/dsl_shared.rb:33:in `require'
        from libraries/aws_backend.rb:60:in `create'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/dsl_shared.rb:47:in `eval'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/dsl_shared.rb:47:in `require'
        from libraries/aws_alb.rb:3:in `load_with_context'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile_context.rb:170:in `instance_eval'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile_context.rb:170:in `load_with_context'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile_context.rb:159:in `load_library_file'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile_context.rb:144:in `block in load_libraries'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile_context.rb:143:in `each'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile_context.rb:143:in `load_libraries'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile.rb:376:in `load_libraries'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile.rb:369:in `block in load_libraries'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile.rb:350:in `each'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile.rb:350:in `each_with_index'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/profile.rb:350:in `load_libraries'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/runner.rb:108:in `block in load'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/runner.rb:102:in `each'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/runner.rb:102:in `load'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/runner.rb:136:in `run'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/cli.rb:304:in `exec'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/base_cli.rb:35:in `start'
        from /usr/local/bundle/gems/cinc-auditor-bin-4.50.3/bin/cinc-auditor:12:in `<top (required)>'
        from /usr/local/bundle/bin/inspec:23:in `load'
        from /usr/local/bundle/bin/inspec:23:in `<main>'
```

**Comment by Nirbhay1997** [comment]
@maxlambnc  could you please tell us what kind of control you are running?

**Comment by maxlambnc** [comment]
We've had this error on different AWS resources, we're not using the aws-sdk-waf module if it helps.

The controls don't run at all, running `inspec exec . -t aws://`  on any one of our controls (for example ec2_instances) will throw the error, and inspec immediately exits.

```ruby
control 'ec2-1' do
  impact 0.8
  title 'test if we have the right number of ec2 instances'
  desc 'fails if the number is too low'

  describe aws_ec2_instances.where(tags: /"eks:cluster-name"=>"#{attribute('eks_cluster_name')}"/) do
    its('instance_ids.cont') { should be >= attribute('expected_ec2_number') }
  end
end
```

Hardcoding the 1.74.71 version, this code snippet works

**Comment by joshedgarva** [comment]
+1, my entire class is having this issue after having successfully used Chef InSpec in a lab 2 weeks ago. Same issue with aws-sdk-waf even though we have no WAF resources in the lab environment, nor do we write any controls for one. This wasn't an issue 2 weeks ago, but it's not clear to me if inspec-aws has been updated since then.

**Comment by Nirbhay1997** [comment]
@joshedgarva  could you please check what version train-aws gem you guys are using?

**Comment by joshedgarva** [comment]
> @joshedgarva could you please check what version train-aws gem you guys are using? try updating it and please let me know.

Unfortunately I know basically nothing about Ruby. We use GitLab CI/CD and simply call the chef/inspec image from Docker Hub, and then use the inspec.yml from this package’s page. The containers are built at runtime and destroyed at exit so the version of Ruby I assume is maintained by whoever maintains the inspec image on Docker Hub. 

I can add a command to my before_script to do some data gathering if you can provide the command I need to run.

**Comment by Nirbhay1997** [comment]
we can check the installed train-aws version using    ` inspec plugin search train-aws`.
if that is outdated, simply update it using `inspec plugin update train-aws`.

**Comment by joshedgarva** [comment]
@Nirbhay1997 
If it helps at all, we get this with inspec detect:

Release:   train-aws: v0.2.22, aws-sdk-core: v3.122.1

**Comment by Nirbhay1997** [comment]
@joshedgarva  Great,  Update the train to the latest

**Comment by joshedgarva** [comment]
> @joshedgarva Great, Update the train to the latest.

Will do, but is there a way to also request that the Docker image maintained by Chef be fixed? This way there would not be errors out of the box.

**Comment by Nirbhay1997** [comment]
@joshedgarva  Could you please point me to the docker image?

**Comment by joshedgarva** [comment]
@Nirbhay1997 Sure, this is the one we use:

https://hub.docker.com/r/chef/inspec

**Comment by Nirbhay1997** [comment]
@joshedgarva  The image was updated 4 hours ago, Is it still happening with the latest image?

**Comment by ABlasakis** [comment]
@Nirbhay1997 i have the same issue, i opened this issue https://github.com/inspec/inspec/issues/5747
As joshedgarva it's doesn't work for me.
i don't understand the link between inspec and inspec-aws with train-aws.

**Comment by ABlasakis** [comment]
I can give you more information.
I use a docker image (ruby:alpine3.13) and we configure like this inspec part :
```
ARG INSPEC_VERSION=4.50.3
ARG GEM_SOURCE=https://rubygems.org
ARG CINC_SOURCE=https://packagecloud.io/cinc-project/stable/

ENV INSPEC_VERSION $INSPEC_VERSION

RUN mkdir -p /share && \
    apk add --update libxml2-dev && \
    gem install --no-document cinc-auditor-bin --version ${INSPEC_VERSION} --clear-sources -s ${CINC_SOURCE} -s ${GEM_SOURCE} && \
    gem install --no-document --source ${GEM_SOURCE} rubocop && \
    apk del build-base && \
    ln -s /usr/local/bundle/bin/cinc-auditor /usr/local/bundle/bin/inspec

VOLUME ["/share"]
```

In my inspec profile, if i set the version 1.74.71, it's work, but if i use an other version like 1.74.72, 1.74.73, 174.82 etc .. i have the error aws-sdk-waf (LoadError) : 
```yml
inspec_version: ">= 4.50"
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.74.71.tar.gz
supports:
  - platform: aws
  ```

**Comment by Nirbhay1997** [comment]
@joshedgarva  @ABlasakis :  This will be fixed in the next container update.

**Comment by Nirbhay1997** [comment]
Closing as the fix was shipped in the latest Docker image

Please reopen , If the issue persist.
