### ISSUE TITLE
Poorly Performing API Call in aws_s3_buckets Resource

### ISSUE THREAD

**Issue by jnikles1** [inspec/inspec-aws#819]
The aws_s3_buckets resource makes an additional call to get the tags of every bucket returned by the list_buckets method. This leads to poor performance when the list_buckets API returns many results.

# Describe the problem
I would expect that the tags are not fetched in the plural resource, since the singular resource fetches the tags anyway.
![image](https://user-images.githubusercontent.com/61483166/149167961-793cf385-d060-404d-86b0-b9d5303b6544.png)

## Possible Solution
Remove the tags field from the plural resource. Allow the end user to fetch tags with the singular resource if they need the tags.

**Comment by sathish-progress** [comment]
yes, this makes sense .. actually `fetch_tags` can be lazy loaded for a particular bucket if needed in plural resource!
