### ISSUE TITLE
Lazy loading not working for aws_iam_users resource

### ISSUE THREAD

**Issue by Rohit1509** [inspec/inspec-aws#896]
Lazy loading bug in aws_iam_users resource

# Describe the problem
Some of the attributes mentioned in the documentation like 'has_console_password' are not working with the above mentioned resource. It is giving out following error: 
```
describe aws_iam_users.where(has_console_password: true).where(has_mfa_enabled: false) do
```
![image](https://user-images.githubusercontent.com/42916862/163037619-12d6d4ed-d4d8-4e4f-a179-76a2be19ec94.png)

## Possible Solution
Fix how the lazy loading is implemented.

**Comment by sathish-progress** [comment]
fixed as part of #898
